<?php

namespace ContainerMlIX1CW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sd_PLueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sd.pLue' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sd.pLue'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'food' => ['privates', '.errored..service_locator.Sd.pLue.App\\Entity\\Food', NULL, 'Cannot autowire service ".service_locator.Sd.pLue": it references class "App\\Entity\\Food" but no such service exists.'],
        ], [
            'food' => 'App\\Entity\\Food',
        ]);
    }
}
