<?php

namespace ContainerMlIX1CW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JWdTOKaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JWdTOKa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JWdTOKa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.JWdTOKa.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.JWdTOKa": it references class "App\\Entity\\Order" but no such service exists.'],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'order' => 'App\\Entity\\Order',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);
    }
}
