<?php

namespace ContainerMlIX1CW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H0QGoQMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H0QGoQM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H0QGoQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.H0QGoQM.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.H0QGoQM": it references class "App\\Entity\\Order" but no such service exists.'],
        ], [
            'order' => 'App\\Entity\\Order',
        ]);
    }
}
