<?php

namespace ContainerMlIX1CW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z1fN4OtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z1fN4Ot' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z1fN4Ot'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'userRespository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
            'slugger' => '?',
            'userRespository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
