<?php

namespace ContainerV6q4bPG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Qbp1JZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Qbp1JZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Qbp1JZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'foodRepository' => ['privates', 'App\\Repository\\FoodRepository', 'getFoodRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'foodRepository' => 'App\\Repository\\FoodRepository',
            'slugger' => '?',
        ]);
    }
}
