<?php

namespace ContainerV6q4bPG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FcewfBBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fcewfBB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fcewfBB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'restaurant' => ['privates', '.errored..service_locator.fcewfBB.App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.fcewfBB": it references class "App\\Entity\\Restaurant" but no such service exists.'],
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
        ], [
            'restaurant' => 'App\\Entity\\Restaurant',
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
        ]);
    }
}
