<?php

namespace ContainerV6q4bPG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..VDWsX1.App\Entity\Booking' shared service.
     *
     * @return \App\Entity\Booking
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..VDWsX1": it references class "App\\Entity\\Booking" but no such service exists.');
    }
}
