<?php

namespace ContainerGTOOV32;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UKLbXedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UKLbXed' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UKLbXed'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.UKLbXed.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.UKLbXed": it references class "App\\Entity\\Order" but no such service exists.'],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.UKLbXed.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.UKLbXed": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'order' => 'App\\Entity\\Order',
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
