<?php

namespace ContainerGTOOV32;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RDK2KCCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rDK2KCC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rDK2KCC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'foodRepo' => ['privates', 'App\\Repository\\FoodRepository', 'getFoodRepositoryService', true],
            'orderRepo' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'restaurantRepo' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categoryRepo' => 'App\\Repository\\CategoryRepository',
            'foodRepo' => 'App\\Repository\\FoodRepository',
            'orderRepo' => 'App\\Repository\\OrderRepository',
            'restaurantRepo' => 'App\\Repository\\RestaurantRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
