<?php

namespace ContainerGTOOV32;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.25Vl3TB.App\Entity\Restaurant' shared service.
     *
     * @return \App\Entity\Restaurant
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.25Vl3TB": it references class "App\\Entity\\Restaurant" but no such service exists.');
    }
}
