<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGTOOV32\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGTOOV32/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGTOOV32.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGTOOV32\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGTOOV32\App_KernelDevDebugContainer([
    'container.build_hash' => 'GTOOV32',
    'container.build_id' => '1e0038be',
    'container.build_time' => 1713361174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGTOOV32');
